project_name: famed-github-backend
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/morphysm/famed-github-backend/internal/devtoolkit/buildinfo.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
dockers:
  - image_templates: ["ghcr.io/morphysm/famed-github-backend:{{ .Version }}"]
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/morphysm/famed-github-backend
      - --label=org.opencontainers.image.source=https://github.com/morphysm/famed-github-backend
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=AGPL3
    extra_files:
      - config.json
nfpms:
  - formats:
      - deb
      - rpm
      - apk
